- type: gameMapPool
  id: DefaultMapPool
  maps:
  - Arena
  # - Saltern #Uncomment these 4 when they've had required features added.
  # - Packed
  # - PackedSM #This one requires special attention as its SM Engine isn't mapped correctly.
  # - Pillar
  - Edge
  - Hammurabi
  - Lighthouse
  - Pebble
  - Shoukou
  - Tortuga
  - TheHive
  #- Submarine
