- type: job
  id: ResearchDirector
  name: job-name-rd
  description: job-description-rd
  playTimeTracker: JobResearchDirector
<<<<<<< HEAD
  antagAdvantage: 6 # DeltaV - Reduced TC: Head of Staff
=======
  antagAdvantage: 6
  requirements:
    - !type:DepartmentTimeRequirement
      department: Epistemics
      time: 54000
    - !type:OverallPlaytimeRequirement
      time: 72000
>>>>>>> my-fork/Psionic-Power-Refactor
  weight: 10
  startingGear: ResearchDirectorGear
  icon: "JobIconResearchDirector"
  requireAdminNotify: true
  supervisors: job-supervisors-captain
  canBeAntag: false
  access:
  - Research
  - Command
  - Maintenance
  - ResearchDirector
<<<<<<< HEAD
  - Mantis # DeltaV - Psionic Mantis, see Resources/Prototypes/DeltaV/Access/epistemics.yml
=======
  - Mantis
  - Chapel
>>>>>>> my-fork/Psionic-Power-Refactor
  - Cryogenics
  special:
  - !type:AddComponentSpecial
    components:
    - type: BibleUser
    - type: PotentialPsionic
    - type: Psionic
      dampening: 1 #Mystagogue gets a significant buff to his antimage abilities, making him better at dispelling than other people
    - type: DispelPower
    - type: CommandStaff
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]

- type: startingGear
  id: ResearchDirectorGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitResearchDirector
    back: ClothingBackpackResearchDirectorFilled
    shoes: ClothingShoesColorBrown
    outerClothing: ClothingOuterCoatRD
    id: RnDPDA
    ears: ClothingHeadsetRD
<<<<<<< HEAD
=======
    belt: BibleMystagogue
>>>>>>> my-fork/Psionic-Power-Refactor
  innerClothingSkirt: ClothingUniformJumpskirtResearchDirector
  satchel: ClothingBackpackSatchelResearchDirectorFilled
  duffelbag: ClothingBackpackDuffelResearchDirectorFilled
